import {randomUUID} from "node:crypto";
import {issueDefinitions} from "@where-they-stand/issue-definitions";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {seedIssues} from "./seed-lib.js";
import {ElectionDataService,PrismaElectionDataRepository,deterministicImportKey,externalIdentifierKey,type CandidateImport} from "../../../services/election-data/src/index";
const enabled=Boolean(process.env.DATABASE_URL); const describeDb=enabled?describe:describe.skip; let db:any;
describeDb("PostgreSQL Phase 1A integrity",()=>{
 let electionId="",raceId="",candidateId="",otherCandidateId="",issueVersionId="";
 beforeAll(async()=>{const {PrismaClient}=await import("@prisma/client");db=new PrismaClient();await seedIssues(db);await seedIssues(db);issueVersionId=(await db.issueVersion.findFirstOrThrow()).id;const election=await db.election.create({data:{name:"Fixture General",cycle:2026,generalDate:new Date("2026-11-03"),status:"ACTIVE",sourceAuthority:"FIXTURE",sourceRecordId:"e-2026",importKey:"fixture|e-2026"}});electionId=election.id;const race=await db.race.create({data:{electionId,office:"HOUSE",state:"CO",district:null,seatClass:null,specialFlag:false,sourceAuthority:"FIXTURE",sourceRecordId:"r-1",importKey:"fixture|r-1"}});raceId=race.id;candidateId=(await db.candidate.create({data:{legalName:"Alex Rivera",displayName:"Alex Rivera"}})).id;otherCandidateId=(await db.candidate.create({data:{legalName:"Alex Rivera",displayName:"Alex Rivera"}})).id});
 afterAll(async()=>{await db.$disconnect()});
 it("rejects changed issue wording against PostgreSQL",async()=>{await expect(seedIssues(db,[{...issueDefinitions[0]!,question:"changed"}])).rejects.toThrow("Refusing to overwrite")});
 it("uses Prisma client UUID defaults without database UUID defaults",async()=>{expect(candidateId).toMatch(/^[0-9a-f-]{36}$/);const defaults=await db.$queryRaw<Array<{column_default:string|null}>>`SELECT column_default FROM information_schema.columns WHERE table_name='Candidate' AND column_name='id'`;expect(defaults[0]?.column_default).toBeNull()});
 it("closes null race uniqueness",async()=>{await expect(db.race.create({data:{electionId,office:"HOUSE",state:"CO",district:null,seatClass:null,specialFlag:false,sourceAuthority:"OTHER",sourceRecordId:"duplicate",importKey:"other|duplicate"}})).rejects.toThrow()});
 it("scopes repeated ballot source records to a race and rejects invalid ballot facts",async()=>{const data={raceId,candidateId,ballotStatus:"PENDING" as const,sourceAuthority:"FEC",sourceRecordId:"one",importKey:"race|fec|one",observedAt:new Date("2026-02-01"),effectiveAt:new Date("2026-01-01")};await Promise.allSettled([db.raceCandidate.create({data}),db.raceCandidate.create({data})]).then(results=>expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1));await expect(db.raceCandidate.create({data:{...data,candidateId:otherCandidateId,sourceRecordId:"negative",importKey:"negative",ballotOrder:-1}})).rejects.toThrow()});
 it("uses persisted candidacy scope when an external identifier belongs to another office and state",async()=>{const wyRace=await db.race.create({data:{electionId,office:"SENATE",state:"WY",district:null,seatClass:"1",specialFlag:false,sourceAuthority:"FIXTURE",sourceRecordId:"wy-senate",importKey:"fixture|wy-senate"}});await db.raceCandidate.create({data:{raceId:wyRace.id,candidateId:otherCandidateId,ballotStatus:"PENDING",sourceAuthority:"FEC",sourceRecordId:"wy-filer",importKey:"wy|filer",observedAt:new Date("2026-01-02"),effectiveAt:new Date("2026-01-01")}});const identifier={authority:"FEC",identifierType:"CANDIDATE_ID",externalId:"S0WY00001",sourceAuthority:"FEC",sourceRecordId:"S0WY00001:2026",electionCycle:2026,verificationMethod:"OFFICIAL_RECORD",verificationStatus:"VERIFIED" as const,confidence:1,observedAt:new Date("2026-01-02")};await db.candidateExternalId.create({data:{candidateId:otherCandidateId,identityKey:externalIdentifierKey(identifier),authority:identifier.authority,identifierType:identifier.identifierType,externalId:identifier.externalId,sourceAuthority:identifier.sourceAuthority,sourceRecordId:identifier.sourceRecordId,electionCycle:identifier.electionCycle,verificationMethod:identifier.verificationMethod,verificationStatus:identifier.verificationStatus,confidence:identifier.confidence,firstObservedAt:identifier.observedAt,lastObservedAt:identifier.observedAt}});const incoming:CandidateImport={raceId,legalName:"Different Name",displayName:"Different Name",office:"HOUSE",state:"CO",cycle:2026,specialElection:false,identifiers:[identifier],ballotStatus:"PENDING",sourceAuthority:"FEC",sourceRecordId:"conflicting-filer",observedAt:new Date("2026-01-03"),effectiveAt:new Date("2026-01-01"),importKey:deterministicImportKey(raceId,"FEC","conflicting-filer")};const service=new ElectionDataService(new PrismaElectionDataRepository(db));expect(await service.importCandidate(incoming)).toMatchObject({kind:"CONFLICT",resolution:{candidateIds:[otherCandidateId]}});expect(await db.raceCandidate.findUnique({where:{raceId_candidateId:{raceId,candidateId:otherCandidateId}}})).toBeNull()});
 it("requires and clears replacement candidate state through the real service",async()=>{const service=new ElectionDataService(new PrismaElectionDataRepository(db));expect(()=>service.setBallotStatus(raceId,candidateId,{status:"REPLACED"} as never)).toThrow("requires replacementCandidateId");const replaced=await service.setBallotStatus(raceId,candidateId,{status:"REPLACED",replacementCandidateId:otherCandidateId},new Date("2026-05-01"));expect(replaced).toMatchObject({ballotStatus:"REPLACED",replacementCandidateId:otherCandidateId,replacedAt:new Date("2026-05-01")});const restored=await service.setBallotStatus(raceId,candidateId,{status:"QUALIFIED"},new Date("2026-05-02"));expect(restored).toMatchObject({ballotStatus:"QUALIFIED",replacementCandidateId:null,replacedAt:null,withdrawnAt:null,disqualifiedAt:null})});
 it("rejects identifier reassignment and permits multiple identifier types",async()=>{const common={authority:"FEC",sourceAuthority:"FEC",electionCycle:2026,verificationMethod:"OFFICIAL_RECORD",verificationStatus:"VERIFIED" as const,confidence:1,firstObservedAt:new Date(),lastObservedAt:new Date()};await db.candidateExternalId.create({data:{candidateId,identityKey:"fec|candidate|h001|2026",identifierType:"CANDIDATE_ID",externalId:"H001",sourceRecordId:"H001",...common}});await db.candidateExternalId.create({data:{candidateId,identityKey:"fec|committee|c001|2026",identifierType:"COMMITTEE_ID",externalId:"C001",sourceRecordId:"C001",...common}});await expect(db.candidateExternalId.create({data:{candidateId:otherCandidateId,identityKey:"fec|candidate|h001|2026",identifierType:"CANDIDATE_ID",externalId:"H001",sourceRecordId:"other",...common}})).rejects.toThrow()});
 it("enforces evidence scope and publication prerequisites",async()=>{const source=await db.source.create({data:{candidateId,type:"CAMPAIGN",url:"https://example.test",retrievedAt:new Date(),hash:"hash"}});const passage=await db.sourcePassage.create({data:{sourceId:source.id,startOffset:0,endOffset:4,text:"text"}});await expect(db.evidence.create({data:{candidateId:otherCandidateId,issueVersionId,sourcePassageId:passage.id,directness:"DIRECT",approvedAt:new Date()}})).rejects.toThrow();const stance=await db.stance.create({data:{candidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await expect(db.stance.update({where:{id:stance.id},data:{status:"PUBLISHED",current:true}})).rejects.toThrow();const evidence=await db.evidence.create({data:{candidateId,issueVersionId,sourcePassageId:passage.id,directness:"DIRECT",approvedAt:new Date()}});await db.stanceEvidence.create({data:{stanceId:stance.id,evidenceId:evidence.id,weightOrder:1}});await db.stance.update({where:{id:stance.id},data:{status:"PUBLISHED",current:true}});const duplicate=await db.stance.create({data:{candidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await db.stanceEvidence.create({data:{stanceId:duplicate.id,evidenceId:evidence.id,weightOrder:1}});await expect(db.stance.update({where:{id:duplicate.id},data:{status:"PUBLISHED",current:true}})).rejects.toThrow()});
 it("requires completed research and verified direct responses",async()=>{const noPosition=await db.stance.create({data:{candidateId:otherCandidateId,issueVersionId,label:"NO_PUBLIC_POSITION",effectiveAt:new Date(),status:"DRAFT"}});await expect(db.stance.update({where:{id:noPosition.id},data:{status:"PUBLISHED",current:true}})).rejects.toThrow();await db.researchJob.create({data:{candidateId:otherCandidateId,issueVersionId,sourceScope:"ALL",status:"COMPLETED",finishedAt:new Date()}});await db.stance.update({where:{id:noPosition.id},data:{status:"PUBLISHED",current:true}});const declined=await db.stance.create({data:{candidateId:otherCandidateId,issueVersionId,label:"DECLINED_TO_STATE",effectiveAt:new Date(),status:"DRAFT"}});await db.campaignResponse.create({data:{candidateId:otherCandidateId,issueVersionId,answer:"DECLINED_TO_STATE",verifiedSubmitter:false}});await expect(db.stance.update({where:{id:declined.id},data:{status:"PUBLISHED"}})).rejects.toThrow();await db.campaignResponse.create({data:{candidateId:otherCandidateId,issueVersionId,answer:"DECLINED_TO_STATE",verifiedSubmitter:true}});await db.stance.update({where:{id:declined.id},data:{status:"PUBLISHED"}})});
 it("prevents cross-scope and branching history",async()=>{const prior=await db.stance.findFirstOrThrow({where:{candidateId,issueVersionId}});await expect(db.stance.create({data:{candidateId:otherCandidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT",supersedesId:prior.id}})).rejects.toThrow();await db.stance.create({data:{candidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT",supersedesId:prior.id}});await expect(db.stance.create({data:{candidateId,issueVersionId,label:"OPPOSES",effectiveAt:new Date(),status:"DRAFT",supersedesId:prior.id}})).rejects.toThrow()});
 it("keeps foreign-key deletion restrictive",async()=>{await expect(db.candidate.delete({where:{id:candidateId}})).rejects.toThrow()});
});

describeDb("persisted candidate identity acceptance",()=>{
 beforeAll(async()=>{if(!db){const {PrismaClient}=await import("@prisma/client");db=new PrismaClient()}});
 afterAll(async()=>{if(db)await db.$disconnect();db=undefined});
 const service=()=>new ElectionDataService(new PrismaElectionDataRepository(db));
 async function race(scope:{office:"HOUSE"|"SENATE";state:string;cycle:number;specialElection:boolean}){
  const suffix=randomUUID();
  const election=await db.election.create({data:{name:`Identity ${suffix}`,cycle:scope.cycle,generalDate:new Date(`${scope.cycle}-11-03`),status:"ACTIVE",sourceAuthority:"IDENTITY_TEST",sourceRecordId:`e-${suffix}`,importKey:`identity|e|${suffix}`}});
  return db.race.create({data:{electionId:election.id,office:scope.office,state:scope.state,district:scope.office==="HOUSE"?"1":null,seatClass:scope.office==="SENATE"?"1":null,specialFlag:scope.specialElection,sourceAuthority:"IDENTITY_TEST",sourceRecordId:`r-${suffix}`,importKey:`identity|r|${suffix}`}});
 }
 function identifier(identifierType:string,externalId:string,cycle:number,record=randomUUID()){
  return {authority:"TEST_AUTHORITY",identifierType,externalId,sourceAuthority:"IDENTITY_TEST",sourceRecordId:record,electionCycle:cycle,verificationMethod:"OFFICIAL_RECORD",verificationStatus:"VERIFIED" as const,confidence:1,observedAt:new Date(`${cycle}-01-02`)};
 }
 async function owner(scope:{office:"HOUSE"|"SENATE";state:string;cycle:number;specialElection:boolean},id:ReturnType<typeof identifier>){
  const ownerRace=await race(scope);const suffix=randomUUID();const candidate=await db.candidate.create({data:{legalName:`Persisted Owner ${suffix}`,displayName:`Persisted Owner ${suffix}`}});
  await db.raceCandidate.create({data:{raceId:ownerRace.id,candidateId:candidate.id,ballotStatus:"QUALIFIED",sourceAuthority:"IDENTITY_TEST",sourceRecordId:randomUUID(),importKey:`identity|ballot|${randomUUID()}`,observedAt:id.observedAt,effectiveAt:new Date(`${scope.cycle}-01-01`)}});
  await db.candidateExternalId.create({data:{candidateId:candidate.id,identityKey:externalIdentifierKey(id),authority:id.authority,identifierType:id.identifierType,externalId:id.externalId,sourceAuthority:id.sourceAuthority,sourceRecordId:id.sourceRecordId,electionCycle:id.electionCycle,verificationMethod:id.verificationMethod,verificationStatus:id.verificationStatus,confidence:id.confidence,firstObservedAt:id.observedAt,lastObservedAt:id.observedAt}});
  return candidate;
 }
 function incoming(target:any,id:ReturnType<typeof identifier>,record=randomUUID()):CandidateImport{const name=`Incoming Person ${record}`;return {raceId:target.id,legalName:name,displayName:name,office:target.office,state:target.state,cycle:target.election.cycle,specialElection:target.specialFlag,identifiers:[id],ballotStatus:"QUALIFIED",sourceAuthority:"IDENTITY_TEST",sourceRecordId:record,observedAt:id.observedAt,effectiveAt:new Date(`${target.election.cycle}-01-01`),importKey:`identity|incoming|${record}`}}
 async function targetRace(scope:{office:"HOUSE"|"SENATE";state:string;cycle:number;specialElection:boolean}){return db.race.findUniqueOrThrow({where:{id:(await race(scope)).id},include:{election:true}})}
 async function expectIdentifierOwner(id:ReturnType<typeof identifier>,candidateId:string){expect(await db.candidateExternalId.findUnique({where:{identityKey:externalIdentifierKey(id)},select:{candidateId:true}})).toEqual({candidateId})}
 async function expectNoIncomingMutation(input:CandidateImport,targetId:string){expect(await db.candidate.findFirst({where:{legalName:input.legalName,displayName:input.displayName}})).toBeNull();expect(await db.raceCandidate.findMany({where:{raceId:targetId}})).toHaveLength(0)}
 async function expectScopedConflict(ownerScope:any,targetScope:any,type="CANDIDATE_ID"){
  const id=identifier(type,randomUUID(),ownerScope.cycle);const existing=await owner(ownerScope,id);const target=await targetRace(targetScope);const input=incoming(target,id);const result=await service().importCandidate(input);expect(result).toMatchObject({kind:"CONFLICT",resolution:{candidateIds:[existing.id]}});await expectNoIncomingMutation(input,target.id);await expectIdentifierOwner(id,existing.id)
 }
 it("keeps the same candidacy identifier separate for a different office",async()=>expectScopedConflict({office:"HOUSE",state:"CO",cycle:2026,specialElection:false},{office:"SENATE",state:"CO",cycle:2026,specialElection:false}));
 it("keeps the same candidacy identifier separate for a different state",async()=>expectScopedConflict({office:"HOUSE",state:"CO",cycle:2026,specialElection:false},{office:"HOUSE",state:"WY",cycle:2026,specialElection:false}));
 it("keeps the same candidacy identifier separate for a different election cycle",async()=>expectScopedConflict({office:"HOUSE",state:"CO",cycle:2026,specialElection:false},{office:"HOUSE",state:"CO",cycle:2028,specialElection:false}));
 it("keeps the same candidacy identifier separate across regular and special elections",async()=>expectScopedConflict({office:"HOUSE",state:"CO",cycle:2026,specialElection:false},{office:"HOUSE",state:"CO",cycle:2026,specialElection:true}));
 it("permits a documented BIOGUIDE stable-person identifier to bridge candidacies",async()=>{const id=identifier("BIOGUIDE_ID",randomUUID(),2026);const existing=await owner({office:"HOUSE",state:"CO",cycle:2026,specialElection:false},id);const target=await targetRace({office:"SENATE",state:"WY",cycle:2028,specialElection:true});const input=incoming(target,{...id,electionCycle:2028});const result=await service().importCandidate(input);expect(result).toMatchObject({kind:"IMPORTED",created:false,candidate:{id:existing.id}});expect(await db.candidate.findFirst({where:{legalName:input.legalName,displayName:input.displayName}})).toBeNull();expect(await db.raceCandidate.findUnique({where:{raceId_candidateId:{raceId:target.id,candidateId:existing.id}}})).not.toBeNull();await expectIdentifierOwner(id,existing.id)});
 it("keeps an unknown identifier type candidacy-scoped",async()=>expectScopedConflict({office:"HOUSE",state:"CO",cycle:2026,specialElection:false},{office:"HOUSE",state:"CO",cycle:2028,specialElection:false},"VENDOR_PERSONISH_ID"));
 it("returns AMBIGUOUS for multiple corroborated in-scope persisted owners without mutation",async()=>{const scope={office:"HOUSE" as const,state:"NM",cycle:2026,specialElection:false};const firstId=identifier("CANDIDATE_ID",randomUUID(),2026);const secondId=identifier("COMMITTEE_ID",randomUUID(),2026);const first=await owner(scope,firstId);const second=await owner(scope,secondId);const target=await targetRace(scope);const input=incoming(target,firstId);input.identifiers=[firstId,secondId];const result=await service().importCandidate(input);expect(result).toMatchObject({kind:"AMBIGUOUS"});expect(new Set(result.resolution.candidateIds)).toEqual(new Set([first.id,second.id]));await expectNoIncomingMutation(input,target.id);await expectIdentifierOwner(firstId,first.id);await expectIdentifierOwner(secondId,second.id)});
 it("returns CONFLICT for incompatible persisted ownership without creating or connecting records",async()=>{const id=identifier("CANDIDATE_ID",randomUUID(),2026);const existing=await owner({office:"SENATE",state:"AK",cycle:2026,specialElection:false},id);const target=await targetRace({office:"HOUSE",state:"FL",cycle:2026,specialElection:false});const input=incoming(target,id);const result=await service().importCandidate(input);expect(result).toMatchObject({kind:"CONFLICT",resolution:{candidateIds:[existing.id]}});await expectNoIncomingMutation(input,target.id);await expectIdentifierOwner(id,existing.id)});
});
