import {randomUUID} from "node:crypto";
import {issueDefinitions} from "@where-they-stand/issue-definitions";
import {afterAll,beforeAll,describe,expect,it} from "vitest";
import {seedIssues} from "./seed-lib.js";
const enabled=Boolean(process.env.DATABASE_URL); const describeDb=enabled?describe:describe.skip; let db:any;
describeDb("PostgreSQL Phase 1A integrity",()=>{
 let electionId="",raceId="",candidateId="",otherCandidateId="",issueVersionId="";
 beforeAll(async()=>{const {PrismaClient}=await import("@prisma/client");db=new PrismaClient();await seedIssues(db);await seedIssues(db);issueVersionId=(await db.issueVersion.findFirstOrThrow()).id;const election=await db.election.create({data:{name:"Fixture General",cycle:2026,generalDate:new Date("2026-11-03"),status:"ACTIVE",sourceAuthority:"FIXTURE",sourceRecordId:"e-2026",importKey:"fixture|e-2026"}});electionId=election.id;const race=await db.race.create({data:{electionId,office:"HOUSE",state:"CO",district:null,seatClass:null,specialFlag:false,sourceAuthority:"FIXTURE",sourceRecordId:"r-1",importKey:"fixture|r-1"}});raceId=race.id;candidateId=(await db.candidate.create({data:{legalName:"Alex Rivera",displayName:"Alex Rivera"}})).id;otherCandidateId=(await db.candidate.create({data:{legalName:"Alex Rivera",displayName:"Alex Rivera"}})).id});
 afterAll(async()=>{await db.$disconnect()});
 it("rejects changed issue wording against PostgreSQL",async()=>{await expect(seedIssues(db,[{...issueDefinitions[0]!,question:"changed"}])).rejects.toThrow("Refusing to overwrite")});
 it("uses Prisma client UUID defaults without database UUID defaults",async()=>{expect(candidateId).toMatch(/^[0-9a-f-]{36}$/);const defaults=await db.$queryRaw<Array<{column_default:string|null}>>`SELECT column_default FROM information_schema.columns WHERE table_name='Candidate' AND column_name='id'`;expect(defaults[0]?.column_default).toBeNull()});
 it("closes null race uniqueness",async()=>{await expect(db.race.create({data:{electionId,office:"HOUSE",state:"CO",district:null,seatClass:null,specialFlag:false,sourceAuthority:"OTHER",sourceRecordId:"duplicate",importKey:"other|duplicate"}})).rejects.toThrow()});
 it("scopes repeated ballot source records to a race and rejects invalid ballot facts",async()=>{const data={raceId,candidateId,ballotStatus:"PENDING" as const,sourceAuthority:"FEC",sourceRecordId:"one",importKey:"race|fec|one",observedAt:new Date("2026-02-01"),effectiveAt:new Date("2026-01-01")};await Promise.allSettled([db.raceCandidate.create({data}),db.raceCandidate.create({data})]).then(results=>expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1));await expect(db.raceCandidate.create({data:{...data,candidateId:otherCandidateId,sourceRecordId:"negative",importKey:"negative",ballotOrder:-1}})).rejects.toThrow()});
 it("rejects identifier reassignment and permits multiple identifier types",async()=>{const common={authority:"FEC",sourceAuthority:"FEC",electionCycle:2026,verificationMethod:"OFFICIAL_RECORD",verificationStatus:"VERIFIED" as const,confidence:1,firstObservedAt:new Date(),lastObservedAt:new Date()};await db.candidateExternalId.create({data:{candidateId,identityKey:"fec|candidate|h001|2026",identifierType:"CANDIDATE_ID",externalId:"H001",sourceRecordId:"H001",...common}});await db.candidateExternalId.create({data:{candidateId,identityKey:"fec|committee|c001|2026",identifierType:"COMMITTEE_ID",externalId:"C001",sourceRecordId:"C001",...common}});await expect(db.candidateExternalId.create({data:{candidateId:otherCandidateId,identityKey:"fec|candidate|h001|2026",identifierType:"CANDIDATE_ID",externalId:"H001",sourceRecordId:"other",...common}})).rejects.toThrow()});
 it("enforces evidence scope and publication prerequisites",async()=>{const source=await db.source.create({data:{candidateId,type:"CAMPAIGN",url:"https://example.test",retrievedAt:new Date(),hash:"hash"}});const passage=await db.sourcePassage.create({data:{sourceId:source.id,startOffset:0,endOffset:4,text:"text"}});await expect(db.evidence.create({data:{candidateId:otherCandidateId,issueVersionId,sourcePassageId:passage.id,directness:"DIRECT",approvedAt:new Date()}})).rejects.toThrow();const stance=await db.stance.create({data:{candidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await expect(db.stance.update({where:{id:stance.id},data:{status:"PUBLISHED",current:true}})).rejects.toThrow();const evidence=await db.evidence.create({data:{candidateId,issueVersionId,sourcePassageId:passage.id,directness:"DIRECT",approvedAt:new Date()}});await db.stanceEvidence.create({data:{stanceId:stance.id,evidenceId:evidence.id,weightOrder:1}});await db.stance.update({where:{id:stance.id},data:{status:"PUBLISHED",current:true}});const duplicate=await db.stance.create({data:{candidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await db.stanceEvidence.create({data:{stanceId:duplicate.id,evidenceId:evidence.id,weightOrder:1}});await expect(db.stance.update({where:{id:duplicate.id},data:{status:"PUBLISHED",current:true}})).rejects.toThrow()});
 it("requires completed research and verified direct responses",async()=>{const noPosition=await db.stance.create({data:{candidateId:otherCandidateId,issueVersionId,label:"NO_PUBLIC_POSITION",effectiveAt:new Date(),status:"DRAFT"}});await expect(db.stance.update({where:{id:noPosition.id},data:{status:"PUBLISHED",current:true}})).rejects.toThrow();await db.researchJob.create({data:{candidateId:otherCandidateId,issueVersionId,sourceScope:"ALL",status:"COMPLETED",finishedAt:new Date()}});await db.stance.update({where:{id:noPosition.id},data:{status:"PUBLISHED",current:true}});const declined=await db.stance.create({data:{candidateId:otherCandidateId,issueVersionId,label:"DECLINED_TO_STATE",effectiveAt:new Date(),status:"DRAFT"}});await db.campaignResponse.create({data:{candidateId:otherCandidateId,issueVersionId,answer:"DECLINED_TO_STATE",verifiedSubmitter:false}});await expect(db.stance.update({where:{id:declined.id},data:{status:"PUBLISHED"}})).rejects.toThrow();await db.campaignResponse.create({data:{candidateId:otherCandidateId,issueVersionId,answer:"DECLINED_TO_STATE",verifiedSubmitter:true}});await db.stance.update({where:{id:declined.id},data:{status:"PUBLISHED"}})});
 it("prevents cross-scope and branching history",async()=>{const prior=await db.stance.findFirstOrThrow({where:{candidateId,issueVersionId}});await expect(db.stance.create({data:{candidateId:otherCandidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT",supersedesId:prior.id}})).rejects.toThrow();await db.stance.create({data:{candidateId,issueVersionId,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT",supersedesId:prior.id}});await expect(db.stance.create({data:{candidateId,issueVersionId,label:"OPPOSES",effectiveAt:new Date(),status:"DRAFT",supersedesId:prior.id}})).rejects.toThrow()});
 it("keeps foreign-key deletion restrictive",async()=>{await expect(db.candidate.delete({where:{id:candidateId}})).rejects.toThrow()});
});
