import {randomUUID} from "node:crypto";
import {afterAll,beforeAll,describe,expect,it} from "vitest";

const enabled=Boolean(process.env.DATABASE_URL); const describeDb=enabled?describe:describe.skip; let db:any;
describeDb("Phase 1 acceptance database enforcement",()=>{
 beforeAll(async()=>{const {PrismaClient}=await import("@prisma/client");db=new PrismaClient()});
 afterAll(async()=>db.$disconnect());
 async function scope(){
  const suffix=randomUUID();
  const [candidate,other]=await Promise.all(["Candidate One","Candidate Two"].map(displayName=>db.candidate.create({data:{legalName:displayName,displayName}})));
  const issue=await db.issue.create({data:{slug:`acceptance-${suffix}`,neutralTitle:"Test",publicCategory:"Test"}});
  const version=await db.issueVersion.create({data:{issueId:issue.id,cycle:2026,version:1,canonicalQuestion:"Question?",goal:"Goal",planJson:{},effectiveAt:new Date("2026-01-01"),status:"ACTIVE",definitionHash:suffix}});
  const otherIssue=await db.issue.create({data:{slug:`other-${suffix}`,neutralTitle:"Other",publicCategory:"Test"}});
  const otherVersion=await db.issueVersion.create({data:{issueId:otherIssue.id,cycle:2026,version:1,canonicalQuestion:"Other?",goal:"Goal",planJson:{},effectiveAt:new Date("2026-01-01"),status:"ACTIVE",definitionHash:`other-${suffix}`}});
  return {candidate,other,version,otherVersion};
 }
 async function publishedEvidence(){
  const s=await scope(); const source=await db.source.create({data:{candidateId:s.candidate.id,type:"CAMPAIGN",url:`https://example.test/${randomUUID()}`,retrievedAt:new Date(),hash:randomUUID()}});
  const passage=await db.sourcePassage.create({data:{sourceId:source.id,startOffset:0,endOffset:4,text:"text"}});
  const evidence=await db.evidence.create({data:{candidateId:s.candidate.id,issueVersionId:s.version.id,sourcePassageId:passage.id,directness:"DIRECT",approvedAt:new Date()}});
  const stance=await db.stance.create({data:{candidateId:s.candidate.id,issueVersionId:s.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-02-01"),status:"DRAFT"}});
  await db.stanceEvidence.create({data:{stanceId:stance.id,evidenceId:evidence.id,weightOrder:1}}); await db.stance.update({where:{id:stance.id},data:{status:"PUBLISHED",current:true}});
  return {...s,source,passage,evidence,stance};
 }
 it("rejects deleting or reassigning the last qualifying stance evidence",async()=>{let x=await publishedEvidence();await expect(db.stanceEvidence.delete({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}}})).rejects.toThrow("published stance lacks");x=await publishedEvidence();const foreign=await db.evidence.create({data:{candidateId:x.other.id,issueVersionId:x.version.id,sourcePassageId:(await db.sourcePassage.create({data:{sourceId:(await db.source.create({data:{candidateId:x.other.id,type:"CAMPAIGN",url:`https://example.test/${randomUUID()}`,retrievedAt:new Date(),hash:randomUUID()}})).id,startOffset:0,endOffset:1,text:"x"}})).id,directness:"DIRECT",approvedAt:new Date()}});await expect(db.stanceEvidence.update({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}},data:{evidenceId:foreign.id}})).rejects.toThrow()});
 it("revalidates both stances when the last evidence association is reassigned",async()=>{const x=await publishedEvidence();const target=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await expect(db.$transaction(async(tx:any)=>{await tx.stanceEvidence.update({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}},data:{stanceId:target.id}});await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE")})).rejects.toThrow("published stance lacks required verification")});
 it("allows evidence reassignment when the old published stance retains support",async()=>{const x=await publishedEvidence();const second=await db.evidence.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,sourcePassageId:x.passage.id,directness:"DIRECT",approvedAt:new Date()}});await db.stanceEvidence.create({data:{stanceId:x.stance.id,evidenceId:second.id,weightOrder:2}});const target=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await db.$transaction(async(tx:any)=>{await tx.stanceEvidence.update({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}},data:{stanceId:target.id}});await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE")});expect(await db.stanceEvidence.findUnique({where:{stanceId_evidenceId:{stanceId:target.id,evidenceId:x.evidence.id}}})).not.toBeNull()});
 it("allows evidence reassignment after the old stance is unpublished",async()=>{const x=await publishedEvidence();const target=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await db.$transaction(async(tx:any)=>{await tx.stance.update({where:{id:x.stance.id},data:{status:"DRAFT",current:false}});await tx.stanceEvidence.update({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}},data:{stanceId:target.id}});await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE")});expect(await db.stanceEvidence.findUnique({where:{stanceId_evidenceId:{stanceId:target.id,evidenceId:x.evidence.id}}})).not.toBeNull()});
 it("rejects deleting, unapproving, or rescoping qualifying evidence",async()=>{let x=await publishedEvidence();await expect(db.evidence.delete({where:{id:x.evidence.id}})).rejects.toThrow();x=await publishedEvidence();await expect(db.evidence.update({where:{id:x.evidence.id},data:{approvedAt:null}})).rejects.toThrow("published stance lacks");x=await publishedEvidence();await expect(db.evidence.update({where:{id:x.evidence.id},data:{candidateId:x.other.id}})).rejects.toThrow();x=await publishedEvidence();await expect(db.evidence.update({where:{id:x.evidence.id},data:{issueVersionId:x.otherVersion.id}})).rejects.toThrow()});
 it("allows evidence changes when another qualifying record remains",async()=>{const x=await publishedEvidence();const second=await db.evidence.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,sourcePassageId:x.passage.id,directness:"DIRECT",approvedAt:new Date()}});await db.stanceEvidence.create({data:{stanceId:x.stance.id,evidenceId:second.id,weightOrder:2}});await db.stanceEvidence.delete({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}}});await db.evidence.update({where:{id:x.evidence.id},data:{approvedAt:null}})});
 it("rejects invalidating or deleting completed research",async()=>{for(const action of ["update","delete"]){const x=await scope();const job=await db.researchJob.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,sourceScope:"ALL",status:"COMPLETED",finishedAt:new Date()}});await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"NO_PUBLIC_POSITION",effectiveAt:new Date(),status:"PUBLISHED"}});const operation=action==="delete"?db.researchJob.delete({where:{id:job.id}}):db.researchJob.update({where:{id:job.id},data:{status:"FAILED"}});await expect(operation).rejects.toThrow("published stance lacks")}});
 it("rejects deleting, changing, or unverifying a declined campaign response",async()=>{for(const change of [{delete:true},{data:{answer:"SUPPORTS"}},{data:{verifiedSubmitter:false}}]){const x=await scope();const response=await db.campaignResponse.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,answer:"DECLINED_TO_STATE",verifiedSubmitter:true}});await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"DECLINED_TO_STATE",effectiveAt:new Date(),status:"PUBLISHED"}});const operation="delete" in change?db.campaignResponse.delete({where:{id:response.id}}):db.campaignResponse.update({where:{id:response.id},data:change.data});await expect(operation).rejects.toThrow("published stance lacks")}});
 it("allows destructive support changes after the stance is unpublished",async()=>{const x=await publishedEvidence();await db.$transaction(async(tx:any)=>{await tx.stance.update({where:{id:x.stance.id},data:{status:"DRAFT",current:false}});await tx.stanceEvidence.delete({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.evidence.id}}})})});
 it("rejects self-reference and chronological reversal",async()=>{const x=await scope();const id=randomUUID();await expect(db.stance.create({data:{id,candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT",supersedesId:id}})).rejects.toThrow();const prior=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-03-01"),status:"DRAFT"}});await expect(db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"OPPOSES",effectiveAt:new Date("2026-02-01"),status:"DRAFT",supersedesId:prior.id}})).rejects.toThrow("chronological")});
 it("rejects two-record and longer cycles",async()=>{let x=await scope();let a=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-01-01"),status:"DRAFT"}});let b=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"OPPOSES",effectiveAt:new Date("2026-02-01"),status:"DRAFT",supersedesId:a.id}});await expect(db.stance.update({where:{id:a.id},data:{supersedesId:b.id,effectiveAt:new Date("2026-03-01")}})).rejects.toThrow("cycle");x=await scope();a=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-01-01"),status:"DRAFT"}});b=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"OPPOSES",effectiveAt:new Date("2026-02-01"),status:"DRAFT",supersedesId:a.id}});const c=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"DIFFERENT_APPROACH",effectiveAt:new Date("2026-03-01"),status:"DRAFT",supersedesId:b.id}});await expect(db.stance.update({where:{id:a.id},data:{supersedesId:c.id,effectiveAt:new Date("2026-04-01")}})).rejects.toThrow("cycle")});
 it("preserves branching and scope protections and permits a linear history",async()=>{const x=await scope();const a=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-01-01"),status:"DRAFT"}});const b=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"OPPOSES",effectiveAt:new Date("2026-02-01"),status:"DRAFT",supersedesId:a.id}});await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"DIFFERENT_APPROACH",effectiveAt:new Date("2026-03-01"),status:"DRAFT",supersedesId:b.id}});await expect(db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-04-01"),status:"DRAFT",supersedesId:a.id}})).rejects.toThrow();await expect(db.stance.create({data:{candidateId:x.other.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date("2026-04-01"),status:"DRAFT",supersedesId:b.id}})).rejects.toThrow("scope");await expect(db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.otherVersion.id,label:"SUPPORTS",effectiveAt:new Date("2026-04-01"),status:"DRAFT",supersedesId:b.id}})).rejects.toThrow("scope")});
});

describeDb("published stance dependency invalidation matrix",()=>{
 beforeAll(async()=>{if(!db){const {PrismaClient}=await import("@prisma/client");db=new PrismaClient()}});
 afterAll(async()=>{if(db)await db.$disconnect();db=undefined});
 async function base(){const suffix=randomUUID();const candidate=await db.candidate.create({data:{legalName:"Dependent Candidate",displayName:"Dependent Candidate"}});const other=await db.candidate.create({data:{legalName:"Other Candidate",displayName:"Other Candidate"}});const issue=await db.issue.create({data:{slug:`dependency-${suffix}`,neutralTitle:"Dependency",publicCategory:"Test"}});const version=await db.issueVersion.create({data:{issueId:issue.id,cycle:2026,version:1,canonicalQuestion:"Question?",goal:"Goal",planJson:{},effectiveAt:new Date(),status:"ACTIVE",definitionHash:suffix}});const otherIssue=await db.issue.create({data:{slug:`dependency-other-${suffix}`,neutralTitle:"Other",publicCategory:"Test"}});const otherVersion=await db.issueVersion.create({data:{issueId:otherIssue.id,cycle:2026,version:1,canonicalQuestion:"Other?",goal:"Goal",planJson:{},effectiveAt:new Date(),status:"ACTIVE",definitionHash:`other-${suffix}`}});return {candidate,other,version,otherVersion}}
 async function evidenceFixture(){const x=await base();async function evidence(candidateId=x.candidate.id,issueVersionId=x.version.id){const source=await db.source.create({data:{candidateId,type:"CAMPAIGN",url:`https://example.test/${randomUUID()}`,retrievedAt:new Date(),hash:randomUUID()}});const passage=await db.sourcePassage.create({data:{sourceId:source.id,startOffset:0,endOffset:4,text:"text"}});const item=await db.evidence.create({data:{candidateId,issueVersionId,sourcePassageId:passage.id,directness:"DIRECT",approvedAt:new Date()}});return {source,passage,item}}const primary=await evidence();const replacement=await evidence();const otherCandidateEvidence=await evidence(x.other.id,x.version.id);const stance=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});const targetStance=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"SUPPORTS",effectiveAt:new Date(),status:"DRAFT"}});await db.stanceEvidence.create({data:{stanceId:stance.id,evidenceId:primary.item.id,weightOrder:1}});await db.stance.update({where:{id:stance.id},data:{status:"PUBLISHED",current:true}});return {...x,stance,targetStance,primary,replacement,otherCandidateEvidence}}
 async function researchFixture(){const x=await base();const job=await db.researchJob.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,sourceScope:"ALL",status:"COMPLETED",finishedAt:new Date()}});const stance=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"NO_PUBLIC_POSITION",effectiveAt:new Date(),status:"PUBLISHED",current:true}});return {...x,job,stance}}
 async function responseFixture(){const x=await base();const response=await db.campaignResponse.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,answer:"DECLINED_TO_STATE",verifiedSubmitter:true}});const stance=await db.stance.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,label:"DECLINED_TO_STATE",effectiveAt:new Date(),status:"PUBLISHED",current:true}});return {...x,response,stance}}
 const evidenceCases=[
  ["StanceEvidence.stanceId reassignment",async(tx:any,x:any)=>tx.stanceEvidence.update({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.primary.item.id}},data:{stanceId:x.targetStance.id}})],
  ["StanceEvidence deletion",async(tx:any,x:any)=>tx.stanceEvidence.delete({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.primary.item.id}}})],
  ["Evidence candidateId change",async(tx:any,x:any)=>tx.evidence.update({where:{id:x.primary.item.id},data:{candidateId:x.other.id,sourcePassageId:x.otherCandidateEvidence.passage.id}})],
  ["Evidence issueVersionId change",async(tx:any,x:any)=>tx.evidence.update({where:{id:x.primary.item.id},data:{issueVersionId:x.otherVersion.id}})],
  ["Evidence approvedAt cleared",async(tx:any,x:any)=>tx.evidence.update({where:{id:x.primary.item.id},data:{approvedAt:null}})],
  ["Evidence deletion",async(tx:any,x:any)=>{await tx.stanceEvidence.delete({where:{stanceId_evidenceId:{stanceId:x.stance.id,evidenceId:x.primary.item.id}}});await tx.evidence.delete({where:{id:x.primary.item.id}})}],
 ] as const;
 const researchCases=[
  ["ResearchJob candidateId change",async(tx:any,x:any)=>tx.researchJob.update({where:{id:x.job.id},data:{candidateId:x.other.id}})],
  ["ResearchJob issueVersionId change",async(tx:any,x:any)=>tx.researchJob.update({where:{id:x.job.id},data:{issueVersionId:x.otherVersion.id}})],
  ["ResearchJob finishedAt cleared",async(tx:any,x:any)=>tx.researchJob.update({where:{id:x.job.id},data:{finishedAt:null}})],
  ["ResearchJob status changed from COMPLETED",async(tx:any,x:any)=>tx.researchJob.update({where:{id:x.job.id},data:{status:"FAILED"}})],
  ["ResearchJob deletion",async(tx:any,x:any)=>tx.researchJob.delete({where:{id:x.job.id}})],
 ] as const;
 const responseCases=[
  ["CampaignResponse candidateId change",async(tx:any,x:any)=>tx.campaignResponse.update({where:{id:x.response.id},data:{candidateId:x.other.id}})],
  ["CampaignResponse issueVersionId change",async(tx:any,x:any)=>tx.campaignResponse.update({where:{id:x.response.id},data:{issueVersionId:x.otherVersion.id}})],
  ["CampaignResponse answer changed from DECLINED_TO_STATE",async(tx:any,x:any)=>tx.campaignResponse.update({where:{id:x.response.id},data:{answer:"SUPPORTS"}})],
  ["CampaignResponse verifiedSubmitter changed to false",async(tx:any,x:any)=>tx.campaignResponse.update({where:{id:x.response.id},data:{verifiedSubmitter:false}})],
  ["CampaignResponse deletion",async(tx:any,x:any)=>tx.campaignResponse.delete({where:{id:x.response.id}})],
 ] as const;
 async function forced(factory:()=>Promise<any>,operation:(tx:any,x:any)=>Promise<any>,unpublish=false){const x=await factory();return db.$transaction(async(tx:any)=>{if(unpublish)await tx.stance.update({where:{id:x.stance.id},data:{status:"DRAFT",current:false}});await operation(tx,x);await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE");return true})}
 it.each(evidenceCases)("rejects invalidating %s at deferred constraint completion",async(_,operation)=>{await expect(forced(evidenceFixture,operation)).rejects.toThrow("published stance lacks required verification")});
 it.each(researchCases)("rejects invalidating %s at deferred constraint completion",async(_,operation)=>{await expect(forced(researchFixture,operation)).rejects.toThrow("published stance lacks required verification")});
 it.each(responseCases)("rejects invalidating %s at deferred constraint completion",async(_,operation)=>{await expect(forced(responseFixture,operation)).rejects.toThrow("published stance lacks required verification")});
 it.each(evidenceCases)("allows %s after the dependent stance is unpublished",async(_,operation)=>{await expect(forced(evidenceFixture,operation,true)).resolves.toBe(true)});
 it.each(researchCases)("allows %s after the dependent stance is unpublished",async(_,operation)=>{await expect(forced(researchFixture,operation,true)).resolves.toBe(true)});
 it.each(responseCases)("allows %s after the dependent stance is unpublished",async(_,operation)=>{await expect(forced(responseFixture,operation,true)).resolves.toBe(true)});
 it("allows ResearchJob deletion when another qualifying completed job remains",async()=>{const x=await researchFixture();await db.researchJob.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,sourceScope:"SECOND",status:"COMPLETED",finishedAt:new Date()}});await expect(db.$transaction(async(tx:any)=>{await tx.researchJob.delete({where:{id:x.job.id}});await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE");return true})).resolves.toBe(true)});
 it("allows CampaignResponse deletion when another verified decline remains",async()=>{const x=await responseFixture();await db.campaignResponse.create({data:{candidateId:x.candidate.id,issueVersionId:x.version.id,answer:"DECLINED_TO_STATE",verifiedSubmitter:true}});await expect(db.$transaction(async(tx:any)=>{await tx.campaignResponse.delete({where:{id:x.response.id}});await tx.$executeRawUnsafe("SET CONSTRAINTS ALL IMMEDIATE");return true})).resolves.toBe(true)});
});
