import {beforeEach,describe,expect,it,vi} from "vitest";
const mocks=vi.hoisted(()=>({issueFindMany:vi.fn(),issueFindUnique:vi.fn(),getElection:vi.fn(),listRaces:vi.fn(),getRace:vi.fn(),getCandidate:vi.fn()}));
vi.mock("@where-they-stand/db",()=>({db:{issue:{findMany:mocks.issueFindMany,findUnique:mocks.issueFindUnique}}}));
vi.mock("@/lib/election-data",()=>({electionData:{getElection:mocks.getElection,listRaces:mocks.listRaces,getRace:mocks.getRace,getCandidate:mocks.getCandidate}}));
const uuid="11111111-1111-4111-8111-111111111111";const now=new Date("2026-01-01");
const race={id:uuid,electionId:uuid,office:"HOUSE",state:"CO",district:null,seatClass:null,specialFlag:false,sourceAuthority:"FIXTURE",sourceRecordId:"race",importKey:"race"};
const candidate={id:uuid,legalName:"Álex Rivera Jr.",displayName:"Alex Rivera"};
const ballot={raceId:uuid,candidateId:uuid,ballotStatus:"QUALIFIED",ballotOrder:null,partyText:"Independent",incumbentFlag:false,fecCandidateId:null,filingStatus:null,withdrawnAt:null,disqualifiedAt:null,replacedAt:null,replacementCandidateId:null,writeIn:false,sourceAuthority:"STATE",sourceRecordId:"ballot",importKey:"ballot",observedAt:now,effectiveAt:now};
const issue={id:uuid,slug:"housing-supply",neutralTitle:"Housing Supply",publicCategory:"Costs and Markets",versions:[{id:uuid,version:1,cycle:2026,canonicalQuestion:"Question?",goal:"Goal",planJson:{},effectiveAt:now,status:"active"}]};
beforeEach(()=>{vi.clearAllMocks();mocks.issueFindMany.mockResolvedValue([issue]);mocks.issueFindUnique.mockResolvedValue(issue);mocks.getElection.mockResolvedValue({id:uuid});mocks.listRaces.mockResolvedValue([race]);mocks.getRace.mockResolvedValue({...race,candidates:[{...ballot,candidate}]});mocks.getCandidate.mockResolvedValue({...candidate,races:[ballot],accounts:[]})});
async function body<T=Record<string,unknown>>(response:Response){return response.json() as Promise<{ok:boolean;data:T}>}
describe("Phase 1A API contracts",()=>{
 it("issues list accepts bounded pagination and rejects unknown fields",async()=>{const {GET}=await import("./issues/route");expect((await body(await GET(new Request("http://test/api/v1/issues?limit=10")))).ok).toBe(true);expect((await GET(new Request("http://test/api/v1/issues?party=x"))).status).toBe(400)});
 it("issue detail validates slug and missing records",async()=>{const {GET}=await import("./issues/[slug]/route");expect((await GET(new Request("http://test"),{params:Promise.resolve({slug:"INVALID_"})})).status).toBe(400);mocks.issueFindUnique.mockResolvedValue(null);expect((await GET(new Request("http://test"),{params:Promise.resolve({slug:"missing"})})).status).toBe(404)});
 it("issue detail returns its strict shape",async()=>{const {GET}=await import("./issues/[slug]/route");expect((await body(await GET(new Request("http://test"),{params:Promise.resolve({slug:"housing-supply"})}))).data.slug).toBe("housing-supply")});
 it("election races validates UUID, query, and missing election",async()=>{const {GET}=await import("./elections/[electionId]/races/route");expect((await GET(new Request("http://test"),{params:Promise.resolve({electionId:"bad"})})).status).toBe(400);expect((await GET(new Request("http://test?extra=1"),{params:Promise.resolve({electionId:uuid})})).status).toBe(400);mocks.getElection.mockResolvedValue(null);expect((await GET(new Request("http://test"),{params:Promise.resolve({electionId:uuid})})).status).toBe(404)});
 it("election races returns a strict bounded list",async()=>{const {GET}=await import("./elections/[electionId]/races/route");const response=await GET(new Request("http://test?limit=1"),{params:Promise.resolve({electionId:uuid})});expect((await body(response)).data).toEqual([expect.objectContaining({state:"CO"})])});
 it("race endpoint validates UUID and missing records",async()=>{const {GET}=await import("./races/[raceId]/route");expect((await GET(new Request("http://test"),{params:Promise.resolve({raceId:"bad"})})).status).toBe(400);mocks.getRace.mockResolvedValue(null);expect((await GET(new Request("http://test"),{params:Promise.resolve({raceId:uuid})})).status).toBe(404)});
 it("race endpoint preserves factual party metadata without ordering by it",async()=>{const {GET}=await import("./races/[raceId]/route");const data=(await body<{candidates:Array<{partyText:string}>}>(await GET(new Request("http://test"),{params:Promise.resolve({raceId:uuid})}))).data;expect(data.candidates[0]!.partyText).toBe("Independent")});
 it("candidate endpoint validates UUID, unknown query, and missing records",async()=>{const {GET}=await import("./candidates/[candidateId]/route");expect((await GET(new Request("http://test"),{params:Promise.resolve({candidateId:"bad"})})).status).toBe(400);expect((await GET(new Request("http://test?unknown=1"),{params:Promise.resolve({candidateId:uuid})})).status).toBe(400);mocks.getCandidate.mockResolvedValue(null);expect((await GET(new Request("http://test"),{params:Promise.resolve({candidateId:uuid})})).status).toBe(404)});
 it("candidate endpoint returns stable person fields and candidacy facts separately",async()=>{const {GET}=await import("./candidates/[candidateId]/route");const data=(await body(await GET(new Request("http://test"),{params:Promise.resolve({candidateId:uuid})}))).data;expect(data).toMatchObject({legalName:"Álex Rivera Jr.",races:[{partyText:"Independent"}]})});
});
