import { readFileSync } from "node:fs";
import { describe,expect,it,vi } from "vitest";
import { deterministicImportKey,ElectionDataService,FixtureFecAdapter,resolveCandidateIdentity,type CandidateImport,type ExternalIdentifierInput,type IdentityCandidate } from "./index";
const fixtures=JSON.parse(readFileSync(new URL("../fixtures/fec-candidates.json",import.meta.url),"utf8")) as unknown[];
const id=(externalId="H0CO01001",cycle=2026):ExternalIdentifierInput=>({authority:"FEC",identifierType:"CANDIDATE_ID",externalId,sourceAuthority:"FEC",sourceRecordId:`${externalId}:${cycle}`,electionCycle:cycle,verificationMethod:"OFFICIAL_RECORD",verificationStatus:"VERIFIED",confidence:1,observedAt:new Date("2026-01-01")});
const person=(changes:Partial<IdentityCandidate>={}):IdentityCandidate=>({id:"one",legalName:"Alex Rivera Jr.",displayName:"Alex Rivera",candidacies:[{office:"HOUSE",state:"CO",cycle:2026,specialElection:false}],identifiers:[id()],...changes});
const input=(changes:Partial<CandidateImport>={}):CandidateImport=>({raceId:"race",legalName:"Alex Rivera",displayName:"Alex Rivera",office:"HOUSE",state:"CO",cycle:2026,specialElection:false,identifiers:[id()],ballotStatus:"PENDING",sourceAuthority:"FEC",sourceRecordId:"H0CO01001:2026",observedAt:new Date("2026-01-01"),effectiveAt:new Date("2026-01-01"),importKey:deterministicImportKey("race","FEC","H0CO01001:2026"),...changes});
describe("candidate identity safety",()=>{
 it("never merges same names without corroboration",()=>expect(resolveCandidateIdentity({...input(),identifiers:[]},[person()])).toMatchObject({kind:"NEW"}));
 it.each([{state:"WY"},{office:"SENATE" as const}])("conflicts when an identifier is reused outside candidacy scope: %j",change=>expect(resolveCandidateIdentity({...input(),...change},[person()])).toMatchObject({kind:"CONFLICT"}));

 it("links stable person identifiers across cycles and special elections while keeping candidacy keys distinct",()=>{expect(resolveCandidateIdentity({...input(),cycle:2028},[person()])).toMatchObject({kind:"MATCH"});expect(resolveCandidateIdentity({...input(),specialElection:true},[person()])).toMatchObject({kind:"MATCH"});expect(deterministicImportKey("race-special","FEC","one")).not.toBe(deterministicImportKey("race-regular","FEC","one"))});
 it("matches through party and name changes because neither decides identity",()=>expect(resolveCandidateIdentity({...input(),legalName:"Alex María Rivera"},[person({legalName:"Alex Rivera",displayName:"A. Rivera"})])).toMatchObject({kind:"MATCH"}));
 it("returns ambiguity instead of choosing among corroborated people",()=>expect(resolveCandidateIdentity(input(),[person(),person({id:"two"})])).toMatchObject({kind:"AMBIGUOUS"}));
 it("does not treat committees as person IDs",()=>{const adapted=new FixtureFecAdapter().normalize({...fixtures[0] as object,principal_committees:["C001","C002"]},{raceId:"race",cycle:2026,observedAt:new Date("2026-01-01")});expect(adapted.identifiers).toHaveLength(1)});
 it("scopes recycled handles by candidate and validity rather than using names",()=>{const handle=(cycle:number)=>({...id("@alex",cycle),authority:"SOCIAL",identifierType:"ACCOUNT_ID"});expect(resolveCandidateIdentity({...input(),identifiers:[handle(2026)]},[person({identifiers:[handle(2024)],candidacies:[{office:"HOUSE",state:"CO",cycle:2024,specialElection:false}]})])).toMatchObject({kind:"NEW"})});
});
describe("imports",()=>{
 it("normalizes FEC filing separately from ballot qualification",()=>expect(new FixtureFecAdapter().normalize(fixtures[0],{raceId:"race",cycle:2026})).toMatchObject({ballotStatus:"PENDING",filingStatus:"C",partyText:"Democratic Party"}));
 it("returns external identifier conflicts for human review",async()=>{const repo=repository();repo.attachExternalIds.mockResolvedValue({kind:"CONFLICT",candidateIds:["other"],identifiers:[id()]});expect(await new ElectionDataService(repo as never).importCandidate(input())).toMatchObject({kind:"CONFLICT"});expect(repo.upsertRaceCandidate).not.toHaveBeenCalled()});
 it("imports an identical fixture twice through the same scoped key",async()=>{const repo=repository();const service=new ElectionDataService(repo as never);await Promise.all([service.importCandidate(input()),service.importCandidate(input())]);expect(repo.upsertRaceCandidate).toHaveBeenCalledTimes(2);expect(repo.upsertRaceCandidate.mock.calls.every(call=>call[0].importKey===input().importKey)).toBe(true)});
 it("preserves write-ins and non-ballot-qualified FEC filers",()=>{expect(input({ballotStatus:"WRITE_IN"}).ballotStatus).toBe("WRITE_IN");expect(input()).toMatchObject({ballotStatus:"PENDING"});expect(input().filingStatus).toBeUndefined()});
 it("requires replacement identity and passes a typed replacement transition",async()=>{const repo=repository();const service=new ElectionDataService(repo as never);expect(()=>service.setBallotStatus("race","one",{status:"REPLACED"} as never)).toThrow("requires replacementCandidateId");await service.setBallotStatus("race","one",{status:"REPLACED",replacementCandidateId:"two"});expect(repo.setBallotStatus).toHaveBeenCalledWith("race","one",{status:"REPLACED",replacementCandidateId:"two"},expect.any(Date))});
});
function repository(){return {getElection:vi.fn(),listRaces:vi.fn(),getRace:vi.fn(),getCandidate:vi.fn(),identityCandidates:vi.fn().mockResolvedValue([person()]),createCandidate:vi.fn(),deleteUnassociatedCandidate:vi.fn(),attachExternalIds:vi.fn().mockResolvedValue({kind:"ATTACHED"}),upsertRaceCandidate:vi.fn().mockResolvedValue({}),setBallotStatus:vi.fn()}}
