import { z } from "zod";
export const CandidateStanceSchema=z.enum(["SUPPORTS","OPPOSES","DIFFERENT_APPROACH","NO_PUBLIC_POSITION","DECLINED_TO_STATE"]);
export type CandidateStance=z.infer<typeof CandidateStanceSchema>;
export const CandidateIdSchema=z.string().uuid().brand<"CandidateId">(); export const RaceIdSchema=z.string().uuid().brand<"RaceId">(); export const ElectionIdSchema=z.string().uuid().brand<"ElectionId">(); export const IssueVersionIdSchema=z.string().uuid().brand<"IssueVersionId">();
export const ApiErrorCodeSchema=z.enum(["INVALID_PATH_PARAMETER","INVALID_QUERY_PARAMETER","NOT_FOUND","INTERNAL_ERROR"]);
export const ApiErrorSchema=z.object({code:ApiErrorCodeSchema,message:z.string()}).strict();
export const ApiResultSchema=<T extends z.ZodType>(data:T)=>z.discriminatedUnion("ok",[z.object({ok:z.literal(true),data}).strict(),z.object({ok:z.literal(false),error:ApiErrorSchema}).strict()]);
export const BallotStatusSchema=z.enum(["PENDING","QUALIFIED","WRITE_IN","WITHDRAWN","DISQUALIFIED","NOT_QUALIFIED","REPLACED"]);
export const VerificationStatusSchema=z.enum(["UNVERIFIED","VERIFIED","DISPUTED","REJECTED"]);
export const ElectionSchema=z.object({id:z.string().uuid(),name:z.string(),cycle:z.number().int(),generalDate:z.coerce.date(),status:z.string(),sourceAuthority:z.string(),sourceRecordId:z.string(),importKey:z.string()}).strict();
export const RaceSchema=z.object({id:z.string().uuid(),electionId:z.string().uuid(),office:z.enum(["HOUSE","SENATE","PRESIDENT","OTHER"]),state:z.string().regex(/^[A-Z]{2}$/),district:z.string().nullable(),seatClass:z.string().nullable(),specialFlag:z.boolean(),sourceAuthority:z.string(),sourceRecordId:z.string(),importKey:z.string()}).strict();
export const CandidateSchema=z.object({id:z.string().uuid(),legalName:z.string(),displayName:z.string()}).strict();
export const RaceCandidateSchema=z.object({raceId:z.string().uuid(),candidateId:z.string().uuid(),ballotStatus:BallotStatusSchema,ballotOrder:z.number().int().nonnegative().nullable(),partyText:z.string().nullable(),incumbentFlag:z.boolean(),fecCandidateId:z.string().nullable(),filingStatus:z.string().nullable(),withdrawnAt:z.coerce.date().nullable(),disqualifiedAt:z.coerce.date().nullable(),replacedAt:z.coerce.date().nullable(),replacementCandidateId:z.string().uuid().nullable(),writeIn:z.boolean(),sourceAuthority:z.string(),sourceRecordId:z.string(),importKey:z.string(),observedAt:z.coerce.date(),effectiveAt:z.coerce.date()}).strict();
export const CandidateAccountSchema=z.object({id:z.string().uuid(),candidateId:z.string().uuid(),platform:z.string(),accountId:z.string(),canonicalUrl:z.string().url(),verificationMethod:z.string(),status:VerificationStatusSchema,sourceAuthority:z.string(),sourceRecordId:z.string(),validFrom:z.coerce.date().nullable(),validUntil:z.coerce.date().nullable(),observedAt:z.coerce.date()}).strict();
export const IssueVersionSchema=z.object({id:z.string().uuid(),version:z.number().int().positive(),cycle:z.number().int(),canonicalQuestion:z.string(),goal:z.string(),planJson:z.unknown(),effectiveAt:z.coerce.date(),status:z.enum(["active","retired"])}).strict();
export const IssueSchema=z.object({id:z.string().uuid(),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),neutralTitle:z.string(),publicCategory:z.string(),versions:z.array(IssueVersionSchema)}).strict();
export const EvidenceReferenceSchema=z.object({id:z.string().uuid(),url:z.string().url(),sourceType:z.string(),publishedAt:z.string().datetime().nullable()}).strict();
export const StanceResultSchema=z.object({candidateId:CandidateIdSchema,issueVersionId:IssueVersionIdSchema,label:CandidateStanceSchema,lastVerifiedAt:z.string().datetime(),evidence:z.array(EvidenceReferenceSchema)}).strict();
export const RaceDetailSchema=RaceSchema.extend({candidates:z.array(RaceCandidateSchema.extend({candidate:CandidateSchema}).strict())}).strict();
export const CandidateDetailSchema=CandidateSchema.extend({races:z.array(RaceCandidateSchema),accounts:z.array(CandidateAccountSchema)}).strict();
export const PaginationSchema=z.object({limit:z.number().int().positive().max(100),offset:z.number().int().nonnegative()}).strict();
